# Generated by Django 6.0.6 on 2026-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('bluesky_did', models.CharField(blank=True, max_length=200)),
                ('bluesky_handle', models.CharField(blank=True, max_length=200)),
                ('mastodon_acct', models.CharField(blank=True, max_length=200)),
                ('mastodon_url', models.URLField(blank=True, max_length=500)),
                ('mastodon_id', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Handle cache',
                'ordering': ['handle'],
            },
        ),
    ]
